name: Teste Node CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  NODE_VERSION: '19.6.0'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    # strategy:
    #   matrix:
    #     node-version: [19.6.0]

    steps:
      - name: Checkout out the repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          # node-version: ${{ matrix.node-version }}

      - name: Npm Ci
        run: npm ci

      - name: Install dependencies
        run: npm install
   
      - name: Build app
        run: npm run build  --if-present
   
      - name: Test app
        run: npm run test

      - name: Njsscan check
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '.' 
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Deploy Fly.io
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --build-target production --remote-only
