name: Teste Node CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # setup:
  #   name: Setup app
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - name: Checkout out the repository
  #       uses: actions/checkout@v3

      # - name: Build image container
      #   run: docker build . --file Dockerfile
  test:
    name: Test app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    # strategy:
    #   matrix:
    #     node-version: [19.6.0]

    steps:
      - name: Checkout out the repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 19.6.0
          # node-version: ${{ matrix.node-version }}

      - name: Npm Ci
        run: npm ci

      - name: Install dependencies
        run: npm install
   
      - name: Build app
        run: npm run build  --if-present
   
      - name: BuiTestld app
        run: npm run test
  # build:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Up container
  #       run: 
