name: Teste Node CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup:
    name: Setup app
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout out the repository
        uses: actions/checkout@v3

      # - name: Build image container
      #   run: docker build . --file Dockerfile
  test:
    name: Test app
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    # strategy:
    #   matrix:
    #     node-version: [19.6.0]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 19.6.0
          # node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install
          npm ci
        working-directory: src
   
      - name: Build and Test app
        run: |
          npm run build
          npm run test
        working-directory: src
  # build:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Up container
  #       run: 
